config/routes.rb
Rails.application.routes.draw do
  #get 'photos/index'
  #get 'photos/new'
  resources :photos
  root "photos#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :title, presence: true
  validates :image_url, presence: true, format: {  with: /.\.(png|jpeg|jpg|gif)/ }
  #validates_format_of :image_url, with: /.\.(png|jpeg|jpg|gif)/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
  end

  #/photos/:id/edit
  def edit
    @id = params[:id]
  end

  # PUT/PATCH/ | /photos/:id
  def update
    photo = Photo.find(params[:id])
    photo.title = params[:photo][:title]
    photo.image_url = params[:photo][:image_url]

    photo.save
    redirect_to photo
  end

  def create
    photo = Photo.new
    photo.title = params[:photo][:title]
    photo.image_url = params[:photo][:image_url]
    
    photo.save
    redirect_to photo #redirect_to "/photos/#{photo.id}"
  end

  # DELETE /photos/:id
  def destroy
    photo = Photo.find(params[:id])
    photo.destroy

    redirect_to photo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationCodes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/edit.html.erb
<h1>Edit photos</h1>

<form action="/photos/<%= @id %>" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="hidden" name="_method" value="PATCH">
  
  <div>
    <label for="title">Titulo</label>
    <input type="text" name="photo[title]" id="title">
  </div>
  <div>
    <label for="image_url">URL de la imagen</label>
    <input type="url" name="photo[image_url]" id="image_url">
  </div>

  <input type="submit" value="Enviar">
</form>

app/views/photos/index.html.erb
<h1>Photos</h1>

<% @photos.each do |photo| %>
  <div>
    <h2><%= photo.title %></h2>
    <p><%= image_tag photo.image_url %></p>
    <%= link_to 'ver', photo_path(photo) %>
  </div>
<% end %>

app/views/photos/new.html.erb
<h1>Photos#new</h1>

<form action="/photos" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div>
    <label for="title">Titulo</label>
    <input type="text" name="photo[title]" id="title">
  </div>
  <div>
    <label for="image_url">URL de la imagen</label>
    <input type="url" name="photo[image_url]" id="image_url">
  </div>

  <input type="submit" value="Enviar">
</form>

app/views/photos/show.html.erb
<h1>Ver registro</h1>
  <div>
    <h2><%= @photo.title %></h2>
    <p><%= image_tag @photo.image_url %></p>
    <%= link_to 'volver al home', root_path %>
    | <%= link_to 'Editar', "/photos/#{@photo.id}/edit" %>
    <%= link_to 'Eliminar', "/photos/#{@photo.id}", method: :delete %>
  </div>